import * as fs from 'node:fs/promises';
import type { Viewpoint } from '../ir/types.js';
import type { RenderedDiagram } from '../renderers/types.js';

export interface InjectionMeta {
  commit?: string | null;
  toolVersion?: string;
}

export async function writeViewpointMarkdown(
  filePath: string,
  viewpoint: Viewpoint,
  diagram: RenderedDiagram,
  meta?: InjectionMeta
): Promise<void> {
  const content = renderViewpointMarkdown(viewpoint, diagram, meta);
  await fs.writeFile(filePath, content, 'utf-8');
}

export function renderViewpointMarkdown(
  viewpoint: Viewpoint,
  diagram: RenderedDiagram,
  meta?: InjectionMeta
): string {
  const lines: string[] = [];
  lines.push('<!--');
  lines.push(
    `  Generated by repolore${meta?.toolVersion ? ' v' + meta.toolVersion : ''}.`
  );
  lines.push('  Do not edit manually — re-run repolore to regenerate.');
  if (meta?.commit) lines.push(`  Source commit: ${meta.commit}`);
  lines.push('-->');
  lines.push('');
  lines.push(`# ${viewpoint.title}`);
  lines.push('');
  if (viewpoint.description) {
    lines.push(viewpoint.description);
    lines.push('');
  }
  if (diagram.truncated) {
    lines.push(
      '> **Note:** Graph exceeded size caps and was pruned by centrality. Adjust with `--max-nodes` / `--max-edges`.'
    );
    lines.push('');
  }
  lines.push('```mermaid');
  lines.push(diagram.source);
  lines.push('```');
  lines.push('');
  lines.push(
    `_Stats: ${diagram.stats.nodeCount} nodes, ${diagram.stats.edgeCount} edges, ${diagram.stats.byteSize} bytes._`
  );
  lines.push('');
  return lines.join('\n');
}
