import * as fs from 'node:fs/promises';
import type { Viewpoint } from '../ir/types.js';
import type { RenderedDiagram } from '../renderers/types.js';
import type { InjectionMeta } from './markdown.js';

export const START_MARKER = '<!-- repolore:start -->';
export const END_MARKER = '<!-- repolore:end -->';

export interface InjectionBlock {
  viewpoint: Viewpoint;
  rendered: RenderedDiagram;
}

export async function injectIntoReadme(
  filePath: string,
  blocks: InjectionBlock[],
  meta?: InjectionMeta
): Promise<void> {
  let existing = '';
  try {
    existing = await fs.readFile(filePath, 'utf-8');
  } catch {
    /* file does not exist; will create */
  }

  const injection = renderInjection(blocks, meta);

  if (!existing) {
    const block = `${START_MARKER}\n${injection}\n${END_MARKER}\n`;
    await fs.writeFile(filePath, block, 'utf-8');
    return;
  }

  const { start, end } = findMarkersOutsideFences(existing);

  let updated: string;
  if (start >= 0 && end > start) {
    const lines = existing.split('\n');
    const before = lines.slice(0, start + 1);
    const after = lines.slice(end);
    updated = [...before, injection, ...after].join('\n');
  } else {
    const block = `${START_MARKER}\n${injection}\n${END_MARKER}`;
    updated = `${existing.trimEnd()}\n\n${block}\n`;
  }

  await fs.writeFile(filePath, updated, 'utf-8');
}

function findMarkersOutsideFences(text: string): { start: number; end: number } {
  // Match only the first START/END pair that lives outside ``` fences.
  // Avoids the failure mode where docs that *show* the marker syntax inside a
  // code block get treated as the injection target.
  const lines = text.split('\n');
  let inFence = false;
  let start = -1;
  let end = -1;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i] ?? '';
    if (/^\s*```/.test(line)) {
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;
    if (line.trim() === START_MARKER && start === -1) {
      start = i;
    } else if (line.trim() === END_MARKER && start >= 0 && end === -1) {
      end = i;
    }
  }
  return { start, end };
}

function renderInjection(blocks: InjectionBlock[], meta?: InjectionMeta): string {
  const out: string[] = [];
  out.push(
    `<!-- Generated by repolore${meta?.toolVersion ? ' v' + meta.toolVersion : ''} -->`
  );
  if (meta?.commit) out.push(`<!-- Source commit: ${meta.commit} -->`);
  out.push('');

  for (const { viewpoint, rendered } of blocks) {
    out.push(`### ${viewpoint.title}`);
    out.push('');
    if (viewpoint.description) {
      out.push(viewpoint.description);
      out.push('');
    }
    out.push('```mermaid');
    out.push(rendered.source);
    out.push('```');
    out.push('');
  }

  return out.join('\n');
}
